// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjjflvdxomgyxqgdsewk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqamZsdmR4b21neXhxZ2RzZXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjIwNDMsImV4cCI6MjA3MDEzODA0M30.0Au4S3TF3Twykjh4UPkjqdkI-hfkSPAyArWDh2NLqiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('Supabase client: SUPABASE_URL is not defined');
  throw new Error('SUPABASE_URL is required');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('Supabase client: SUPABASE_PUBLISHABLE_KEY is not defined');
  throw new Error('SUPABASE_PUBLISHABLE_KEY is required');
}

let storage;
try {
  storage = localStorage;
} catch (error) {
  console.warn('Supabase client: localStorage not available, using memory storage:', error);
  storage = {
    getItem: () => null,
    setItem: () => {},
    removeItem: () => {},
    clear: () => {},
    key: () => null,
    length: 0
  };
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'centrabudget-web'
    }
  }
});

// Test connection and session detection
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.warn('Supabase client: Initial connection test failed:', error.message);
  }
});

// Listen for auth state changes globally
supabase.auth.onAuthStateChange((event, session) => {
  // Handle email verification specifically
  if (event === 'SIGNED_IN' && session?.user) {
    if (session.user.email_confirmed_at) {
      // Store new user flag for onboarding
      try {
        localStorage.setItem('centrabudget_newUser', 'true');
        localStorage.setItem('centrabudget_welcomeShown', 'false');
      } catch {}
    }
  }
});